---
- name: Ensure /usr/local/bin exists
  file:
    path: /usr/local/bin
    state: directory
    mode: '0755'

- name: Install common tools
  block:
    - name: Download tool {{ item.name }}
      get_url:
        url: "{{ item.url }}"
        dest: "/tmp/{{ item.name }}-{{ item.version }}.{{ 'tar.gz' if item.type == 'tar' else 'bin' }}"
        mode: '0755'
      when: item.type is defined
      register: download_result

    - name: Extract and move {{ item.name }} binary
      unarchive:
        src: "/tmp/{{ item.name }}-{{ item.version }}.tar.gz"
        dest: "/tmp/{{ item.name }}-{{ item.version }}"
        remote_src: yes
      when: item.type == 'tar'

    - name: Move {{ item.name }} binary to {{ item.dest }}
      copy:
        src: "/tmp/{{ item.name }}-{{ item.version }}/{{ item.binary_path_in_tar | default(item.name) }}"
        dest: "{{ item.dest }}"
        mode: '0755'
      when: item.type == 'tar'

    - name: Remove temp files for {{ item.name }}
      file:
        path: "/tmp/{{ item.name }}-{{ item.version }}"
        state: absent
      when: item.type == 'tar'
  loop: "{{ common_tools }}"
