---
- name: Stop K3s service
  ansible.builtin.systemd:
    name: k3s
    state: stopped
    enabled: no
  ignore_errors: yes

- name: Uninstall K3s
  ansible.builtin.shell: /usr/local/bin/k3s-uninstall.sh
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Remove kubeconfig
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube/config"
    state: absent
  ignore_errors: yes

- name: Remove K3s directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/rancher/k3s
    - /var/lib/rancher/k3s
    - /var/lib/rancher/agent
  ignore_errors: yes
