---
- name: Add Jetstack Helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    state: present
  when: (rancher_tls_source is defined and rancher_tls_source in ["rancher", "letsEncrypt"]) and not ansible_check_mode
  



- name: Install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    namespace: cert-manager
    create_namespace: yes
    release_values:
      installCRDs: true
    state: present
    wait: yes                  # Wait for all resources to be ready
    wait_timeout: 120s          # Wait up to 300 seconds (5 minutes)
  when: not ansible_check_mode
